name: Build XCFramework

on:
  push:
    branches:
    - master
    tags:
    - "*"
  pull_request:

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode:
          - 11.4
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Select Xcode
      run: sudo xcode-select --switch /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Build MRuby
      run: ./build.sh
    - name: Make XCFramework
      run: ./make-xcframework.sh
    - uses: actions/upload-artifact@v2
      with:
        name: libmruby.xcframework
        path: libmruby.xcframework
  release:
    runs-on: macOS-latest
    needs: build
    if: contains(github.ref, 'tags/')
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: libmruby.xcframework
        path: libmruby.xcframework
    - name: Create zip
      run: zip -r libmruby.xcframework.zip libmruby.xcframework
    - name: Activate GitHub App token
      id: generate_github_token
      uses: tibdex/github-app-token@v1.0.2
      with:
        app_id: ${{ secrets.PODUPDATER_APP_ID }}
        private_key: ${{ secrets.PODUPDATER_PRIVATE_KEY }}
    - name: Checkout PodsSpecs
      uses: actions/checkout@v2
      with:
        token: ${{ steps.generate_github_token.outputs.token }}
        repository: cinderella-project/PodsSpecs
        path: '~/.cocoapods/repos/cinderella'
    - name: Upload to PodsSpecs
      run: pod repo push cinderella libmruby.podspec
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload XCFramework
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./libmruby.xcframework.zip
        asset_name: libmruby.xcframework.zip
        asset_content_type: application/zip